### ISSUE TITLE
Build failure on Windows (GCC v14.2.0 / Rack v2.5.x DEBUG build from source)

### ISSUE THREAD

**Issue by SteveRussell33** [Bloodbat/SanguineMonsters#1]
```
g++ -o plugin.dll build/src/aion.cpp.o build/src/alchemist.cpp.o build/src/alembic.cpp.o build/src/brainz.cpp.o build/src/bukavac.cpp.o build/src/dollyx.cpp.o build/src/dungeon.cpp.o build/src/kitsune.cpp.o build/src/medusa.cpp.o build/src/monstersblank.cpp.o build/src/oraculus.cpp.o build/src/oubliette.cpp.o build/src/plugin.cpp.o build/src/raiju.cpp.o build/src/sanguinecomponents.cpp.o build/src/sanguinehelpers.cpp.o build/src/sphinx.cpp.o build/src/superswitch18.cpp.o build/src/superswitch81.cpp.o build/src/werewolf.cpp.o build/pcg/pcg-advance-128.c.o build/pcg/pcg-advance-16.c.o build/pcg/pcg-advance-32.c.o build/pcg/pcg-advance-64.c.o build/pcg/pcg-advance-8.c.o build/pcg/pcg-global-32.c.o build/pcg/pcg-global-64.c.o build/pcg/pcg-output-128.c.o build/pcg/pcg-output-16.c.o build/pcg/pcg-output-32.c.o build/pcg/pcg-output-64.c.o build/pcg/pcg-output-8.c.o build/pcg/pcg-rngs-128.c.o build/pcg/pcg-rngs-16.c.o build/pcg/pcg-rngs-32.c.o build/pcg/pcg-rngs-64.c.o build/pcg/pcg-rngs-8.c.o -shared -L../.. -lRack -static-libstdc++
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/pcg/pcg-rngs-64.c.o: in function `pcg_setseq_64_xsh_rr_32_boundedrand_r':
C:\_Projects\VCVRack\V2\Rack\plugins\SanguineMonsters/pcg/pcg_variants.h:1359: multiple definition of `pcg_setseq_64_xsh_rr_32_boundedrand_r'; build/src/oraculus.cpp.o:C:\_Projects\VCVRack\V2\Rack\plugins\SanguineMonsters/./pcg/pcg_variants.h:1359: first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [../../compile.mk:79: plugin.dll] Error 1
```

**Comment by Bloodbat** [comment]
Oh wow... that's weird.
I can't reproduce it, under Windows or Linux, under either the main or the monstersdev branches, from a fresh git clone, with GCC 14.2 as well and Rack 2.5.2 (the whole thing, not the toolkit).
VCV didn't have that problem either: the plugin's now available in the Library, and I know they notify authors when plugins fail to build under one of the platforms.
Is the problem consistent?

**Comment by SteveRussell33** [comment]
Just tried again with a clean repo clone after nuking the previous one; still the same error.

**Comment by Bloodbat** [comment]
I still can't reproduce it anywhere :S
Windows, Linux or Docker for building Linux and Mac.

I, however, tried a couple of things, maybe they will fix it? Can you please try to build it from the weirdmsys branch?

I really can't figure out why it's failing for you other than, for some reason, your GCC ignoring the

```
#if __cplusplus
extern "C" {
#endif
```
in pcg_variants.h

Or some weird or non standard config / setting / variable / flag in your build environment or in the rack make files. :S

**Comment by SteveRussell33** [comment]
OK that branch works...  mainly I assume because of the ``makefile`` edit - I understand your point but can't work it either myself. 
Changed issue title to better reflect my build environment.

**Comment by Bloodbat** [comment]
I'm glad it does.

I'm keeping the changes:  someone could have the same problem, better safe than sorry.

All the default debug config does is call gdb, it doesn't even change the O3... that's not really debugger friendly... so... it's a mystery.

Thanks for the report and the help :)

**Comment by SteveRussell33** [comment]
Funny you say that, I've changed the optimization line in my ``compile.mk`` file from ``-O3`` to ``-Og`` as per GCC docs for my custom Rack build, I changed it back as part of testing with this issue. Didn't make a difference.

**Comment by Bloodbat** [comment]
Yeah, it shouldn't.
There is one GCC option that could affect this particular issue; but I can't remember it off the top of my head... and it's usually not related to debugging.

**Comment by Bloodbat** [comment]
Oh right! You mentioned MSYS' GCC 14.2...
I don't know if you've seen the discussion about that; but in case you haven't... don't nuke your deps or you won't be able to build Rack out of the box.
I have a repo with a fix for that; but Rack doesn't accept PRs... so, their stock source will not build.

**Comment by SteveRussell33** [comment]
Yeah I've seen that thread. 
When there's an update patch to Rack, I keep the ``deps`` folder as it is (I have a backup as well - as a good working copy) and I just simply do a PR for to my own repo and then build locally as before, simple smooth process.

**Comment by Bloodbat** [comment]
I keep a backup as well; but it bothers me when stuff doesn't build :P
